// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiAienpdSn_Yyfj5YIbDP7xFWmJi-UpS4',
    appId: '1:366425153645:web:6e2d726020a444cbc5df64',
    messagingSenderId: '366425153645',
    projectId: 'visitor-management-syste-98ed6',
    authDomain: 'visitor-management-syste-98ed6.firebaseapp.com',
    storageBucket: 'visitor-management-syste-98ed6.firebasestorage.app',
    measurementId: 'G-6JBXN8D7DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDFC4khMVnjR2bbzzsyo-MmmbXfDon0cY',
    appId: '1:366425153645:android:3236f3da3458b534c5df64',
    messagingSenderId: '366425153645',
    projectId: 'visitor-management-syste-98ed6',
    storageBucket: 'visitor-management-syste-98ed6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4FcszlrgLNA_fgtYAXMBDOYw4cPFieYQ',
    appId: '1:366425153645:ios:19d5e4731e9b2b24c5df64',
    messagingSenderId: '366425153645',
    projectId: 'visitor-management-syste-98ed6',
    storageBucket: 'visitor-management-syste-98ed6.firebasestorage.app',
    iosBundleId: 'com.example.visitorManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4FcszlrgLNA_fgtYAXMBDOYw4cPFieYQ',
    appId: '1:366425153645:ios:19d5e4731e9b2b24c5df64',
    messagingSenderId: '366425153645',
    projectId: 'visitor-management-syste-98ed6',
    storageBucket: 'visitor-management-syste-98ed6.firebasestorage.app',
    iosBundleId: 'com.example.visitorManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiAienpdSn_Yyfj5YIbDP7xFWmJi-UpS4',
    appId: '1:366425153645:web:05ef7b178b331351c5df64',
    messagingSenderId: '366425153645',
    projectId: 'visitor-management-syste-98ed6',
    authDomain: 'visitor-management-syste-98ed6.firebaseapp.com',
    storageBucket: 'visitor-management-syste-98ed6.firebasestorage.app',
    measurementId: 'G-YLE8V21TNS',
  );
}
